### ISSUE TITLE
Problem with templates selector

### ISSUE THREAD

**Issue by LaBisquerie** [PrestaSafe/prettyblocks#102]
Before the V2, the champ templates, like this : 
`'templates' => [
      'default' =>  'module:'.$this->name.'/views/templates/block/default.tpl',
      'test' => 'module:'.$this->name.'/views/templates/block/test.tpl',
],`
this worked, but now the selected template is not updated in the block, making this field non-functional.

**Comment by PrestaSafe** [comment]
Fixed https://github.com/PrestaSafe/prettyblocks/pull/103

**Comment by LaBisquerie** [comment]
Thanks !
