### ISSUE TITLE
MultiSelect not diplayed if f.value is empty

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaSafe/prettyblocks#127]
In the PanelSettings, the MultiSelect Component is not displayed is his value is "". 

<img width="353" alt="Capture d’écran 2023-07-28 à 18 17 28" src="https://github.com/PrestaSafe/prettyblocks/assets/4788787/764e1e2e-6d73-48de-9812-0e0aa3e9e5c0">

**Comment by micka-fdz** [comment]
Is this not normal? I seem to remember that this field expects an array as input.

@jf-viguier can you confirm ?

**Comment by PrestaSafe** [comment]
Nope, not normal, i've fixed it in https://github.com/PrestaSafe/prettyblocks/tree/remove-lang-table 
I've some improuvements to add (for settings) and it's gonna be OK.
