### ISSUE TITLE
Troubleshooting on multistore

### ISSUE THREAD

**Issue by cyrielle-vuillemin** [PrestaSafe/prettyblocks#13]
Hello !

I spotted a problem in multistore with the "selector" type with the "Category" collection.

Here is the detail :

- The multistore mode is activated (id_shop 1 and id_shop 2)
- The products are common between the shops
- The category is common between stores
- I created a block:

```
$blocks[] = [
     'name' => $this->l('Products from category'),
     'description' => $this->l('Products from category'),
     'code' => 'featured_product',
     'tab' => 'general',
     'icon' => 'GiftIcon',
     'need_reload' => true,
     'templates' => [
         'default' => 'module:'.$this->name.'/views/templates/blocks/slider-products.tpl'
     ],
     'config' => [
         'fields' => [
             'category' => [
                 'type' => 'selector',
                 'label' => 'Category',
                 'collection' => 'Category',
                 'default' => '2',
                 'selector' => '{id} - {name}'
             ],
             'title' => [
                 'type' => 'text',
                 'default' => 'Our products',
                 'label' => 'Title'
             ]
         ],
     ],
];
```

Result :
- On the id_shop 1 store, the products of the category are well reported
- On the id_shop 2 store, the blocks.extra.products is false

I tried to trace the track I have the impression that there is a blockage in the formatFieldSelector function see in Configuration::get(), but I can't find a conclusive track...

Do you have an idea ?
Thanks in advance !

**Comment by PrestaSafe** [comment]
Hi. Sorry for this issue. 
I actually can't check this week 

I'll make some tests next week. If i have the same issue i'll fix it. 

Maybe that context is not send to controller. I'll let you know.

**Comment by cyrielle-vuillemin** [comment]
Hello,

I've been looking into this a bit, I noticed that when creating a block in the `ps_configuration` table the row is added with the main shop id.

I tried to remove the shop id in the column `id_shop` to put NULL and my block appears well in the 2 shops.

If I use prettyblock in a different shop context, prettyblock does not work (displays "loading"). Maybe this is related?

I hope I'm clear in what I'm saying.

**Comment by adn34** [comment]
> Hello,
> 
> I've been looking into this a bit, I noticed that when creating a block in the `ps_configuration` table the row is added with the main shop id.
> 
> I tried to remove the shop id in the column `id_shop` to put NULL and my block appears well in the 2 shops.
> 
> If I use prettyblock in a different shop context, prettyblock does not work (displays "loading"). Maybe this is related?
> 
> I hope I'm clear in what I'm saying.

The "loading" issue is because the iframe displaying your website is loading with a different url than the current shop context so it gets blocked by crossorigin policies, at least this is what I noticed in my case.
