### ISSUE TITLE
Rename `magic_zone` Smarty plugin

### ISSUE THREAD

**Issue by micka-fdz** [PrestaSafe/prettyblocks#15]
I think we need to rename `magic_zone` Smarty plugin to something more related to module name.

Current: `{magic_zone zone_name="myCustomZone"}` 
New: `{prettyblocks_zone name="myCustomZone"}`

**Comment by PrestaSafe** [comment]
Hi, we will make an alias for avoiding breaking changes for now. 
Thanks to you
