### ISSUE TITLE
Prettyblocks 3.0

### ISSUE THREAD

**Issue by fregeac** [PrestaSafe/prettyblocks#152]
Ce module ne fonctionne pas avec Prestashop 8.1.2
Fichier .zip de module non valide

**Comment by PrestaSafe** [comment]
Effectivement, le zip est mal formatté. Nous corrigeons ça dans la journée. 
Merci de nous l'avoir signalé. 
Cordialement

**Comment by PrestaSafe** [comment]
Nous avons corrigé le fichier et profité pour corriger un petit soucis que nous venons de rencontrer, nous vous invitons à prendre la dernière release 3.0.1 : https://github.com/PrestaSafe/prettyblocks/releases/tag/3.0.1
Cordialement
