### ISSUE TITLE
500 Server Error when trying to add a hook block from EverBlock

### ISSUE THREAD

**Issue by MekaClaude** [PrestaSafe/prettyblocks#159]
I use PrettyBlocks with Ever Block on a PrestaShop 1.7.6.5 on a shared server. 
When I try to add a Hook block on a home page, this error appears. 
I just deactivate the module to get the home page working again. 

<img width="1144" alt="500 SERVER ERROR" src="https://github.com/PrestaSafe/prettyblocks/assets/20024130/51a3035a-a32c-4df3-8cec-7af9c26609f5">

**Comment by MekaClaude** [comment]
It was impossible to remove the hook block from EverBlock. I just reset ( réinitialiser ) PrettyBlock, so I can use it again. 
Unfortunately, all the custom block are lost. I have to add them one by one.

**Comment by PrestaSafe** [comment]
Hi, please activate your debug mode and send the erreur message. 
Thansk
