### ISSUE TITLE
Fileupload field not working in repeater

### ISSUE THREAD

**Issue by answeb** [PrestaSafe/prettyblocks#160]
When I add a fileupload field in a repeater, it does not appear in the repeated block.
However it does work in the 'config' section.
Prettyblocks 3.0.2 / PS8.1.2 / PHP8.1

**Comment by PrestaSafe** [comment]
Hi, can you install and test this module please ? 
https://github.com/PrestaSafe/prettyblockstestfields

this module allows you to test all available field. 
fileUpload works fine for me.

**Comment by answeb** [comment]
Hi, I understood why  I thought it didn't work : I am creating a module that adds several blocks to prettyblocks, and when you edit a repeated group, it doesn't "reread" the blocks returned by the module. It rereads its json configuration from database : my new field wasn't showing until I created a new block (or delete and recreate it). It is the same for all files in the repeater.
It's kind of confusing but since it's only for developpers, it is acceptable. It should be mentionned though, because it doesn't happen in the "config" section
