### ISSUE TITLE
The editor does not load correctly.

### ISSUE THREAD

**Issue by Luifer-dnk** [PrestaSafe/prettyblocks#166]
The editor does not load correctly.

https://github.com/PrestaSafe/prettyblocks/assets/31345705/7d8aaf27-25b5-415b-a3ec-31d5be24f57a

Could it be a problem with loading some .js through "cloudflare"?

PS 8.1.2
PHP 8.1.25

The same tests performed on localhost work perfectly.

Many thanks.

**Comment by Luifer-dnk** [comment]
**Solved.**

In Cloudflare you have to disable Rocket Loader loading.

**Comment by Luifer-dnk** [comment]
**Solved**.

In Cloudflare you have to disable Rocket Loader loading.

**Comment by PrestaSafe** [comment]
Thanks for your reply !
