### ISSUE TITLE
 Illegal string offset

### ISSUE THREAD

**Issue by A2P2R** [PrestaSafe/prettyblocks#179]
Hello, I've had an error message for some time now (without any particular action). 

> Warning: Illegal string offset 'show' in /modules/prettyblocks/classes/prettyblocks/core/FieldCore.php on line 609
> 
> Warning: Illegal string offset 'id' in 
> /modules/prettyblocks/classes/prettyblocks/core/FieldCore.php on line 609

What is the reason for this? thank you

**Comment by PrestaSafe** [comment]
Hi, we fixed this in the 3.0.5 (HelperBuilder)
