### ISSUE TITLE
Allow multiple values on some fields

### ISSUE THREAD

**Issue by micka-fdz** [PrestaSafe/prettyblocks#18]
Add possibility to select multiple values on `selector` and `select` fields. Maybe also for checkboxes.

Maybe with an `multiple` boolean option.

**Comment by micka-fdz** [comment]
I like SF approach for choices fields (select, radio buttons and checkboxes).
https://symfony.com/doc/current/reference/forms/types/choice.html

**Comment by PrestaSafe** [comment]
add in #101
