### ISSUE TITLE
Remove default block options

### ISSUE THREAD

**Issue by PubliAlex** [PrestaSafe/prettyblocks#188]
Hello,

I didn't find in the doc how to remove the block default options. It's not relevant in my case I would like to remove them, how to do that ?

![image](https://github.com/PrestaSafe/prettyblocks/assets/55833027/d0137dcd-807c-463a-ba0a-c976ba98f494)

Thank you

**Comment by PrestaSafe** [comment]
We can't do this for now. It's a good idea btw.

**Comment by PubliAlex** [comment]
Ok thank you, I will hide them using CSS by waiting a real solution.

**Comment by PubliAlex** [comment]
I see its marked as completed, is it done ? Do you have some documentation about how to remove default block option ?

**Comment by PubliAlex** [comment]
> i did a mistake, it's not done and it won't be for now, this is not a priority for us. You can, if you submit a PR for that.

OK understood, would it be possible, at least, to add some classes to default parameters to be able to target them in CSS in order to hide them ? Cause actually, there is nothing that I could target to hide them.

Thank you
