### ISSUE TITLE
Blocks disponibles vide

### ISSUE THREAD

**Issue by cromatyt** [PrestaSafe/prettyblocks#193]
Bonjour,

Déjà merci pour ce projet.

Je souhaitais tester votre module mais j'ai rencontré le problème suivant.
Lorsque je clique sur "ajouter un nouvel élement", la liste des blocks disponibles est vide :
![presta1](https://github.com/PrestaSafe/prettyblocks/assets/94718988/0b0b3b65-c92d-4d23-8f0a-164d5c5cc3ae)

De plus dès que je clique sur "Paramètres du thème", celui-ci disparait (div id=themeSettingsPanel).
![presta2](https://github.com/PrestaSafe/prettyblocks/assets/94718988/3af2e05c-be4c-423f-bff1-97094cc12549)
![presta3](https://github.com/PrestaSafe/prettyblocks/assets/94718988/ea7269fb-d0ca-468a-ae40-d539d18abb03)

Environnement :
Prestashop déployé via docker, image prestashop/prestashop:8.1.3-8.1-apache
Module prettyblocks version 3.0.4
Fresh install, aucun autre module installé mis à part ceux part défaut.
Testé sur Firefox 122.0 et Chrome 120.0.6099.225.
Aucune erreur dans la console du navigateur et toutes les requêtes répondent en 200.

Merci d'avance

**Comment by PrestaSafe** [comment]
Bonjour, 
PrettyBlocks arrive "vide" c'est normal, seul un module peut remplir des blocks. 
Vous pouvez utiliser les classicblocks pour cela: https://github.com/PrestaSafe/classicblocks
Vous aurez également des settings qui vont s'ajouter. 

Cordialement
