### ISSUE TITLE
Load in progress

### ISSUE THREAD

**Issue by speedlightoulouse** [PrestaSafe/prettyblocks#197]
Hello after installing the module and launching it load the home page loads and stays on loading
I am using PrestaShop 8.0.2

an idea ?

Thanks for your help

**Comment by OctaYann** [comment]
ping !
i've got the same error, it looks like i.prestashop.* is not defined at all ...
Any infos ?

**Comment by OctaYann** [comment]
> ping ! i've got the same error, it looks like i.prestashop.* is not defined at all ... Any infos ?

my bad ! That's not a problem with prettyblocks for me !

**Comment by PrestaSafe** [comment]
i close this issue :)
