### ISSUE TITLE
Tinymce issue

### ISSUE THREAD

**Issue by OctaYann** [PrestaSafe/prettyblocks#202]
After using a migration module to migrate data from the old prestashop version of my client, i can't use tinymce anymore in prettyblocks.

I got this error

`"no-api-key" is not entitled to further Tiny Cloud editor loads.
All created TinyMCE editors are now configured to be read-only.`

Can i queekly fix it ?

**Comment by PrestaSafe** [comment]
Hi, thankf for your report, have this issue also. 

This is an update from TinyMCE https://www.tiny.cloud/docs/tinymce/latest/invalid-api-key/
editor now need an api key. 
I'll fix it soon, i'll make something to enter the api key in prettyblocks. 

Thanks

**Comment by OctaYann** [comment]
So i'll need to pay for tiny mce or i'ts still free ?
I need to create an api key for each of our clients ?

**Comment by PrestaSafe** [comment]
You have a free plan: https://www.tiny.cloud/pricing/ 
I think i'll remove tinyMCE in futur version. 

Considere it like a quick fix :) 

I don't want any paid plugin in PrettyBlocks Core. 

Thanks.

**Comment by OctaYann** [comment]
Ok thx, i'll try it during the day.
Thanks for this fast answer !

**Comment by OctaYann** [comment]
Can you give me the place where i should put my api key ?

**Comment by CySSoO** [comment]
@OctaYann you can edit JS file located on this folder
 /modules/prettyblocks/build/assets
search for "no-api-key" and replace it with your own key
Don't forget to allow domain on your TinyMCE account

**Comment by OctaYann** [comment]
Thank you so much @CySSoO, you literally save me maybe hours and my migration 🙏

Waiting for official path, thank you all

**Comment by PrestaSafe** [comment]
Thanks to @CySSoO for the tips, the fix coming soon :)

**Comment by PrestaSafe** [comment]
You can see how to fix it here: https://github.com/PrestaSafe/prettyblocks/wiki
