### ISSUE TITLE
Problème avec TinyMCE et le champ "editor"

### ISSUE THREAD

**Issue by Drenore** [PrestaSafe/prettyblocks#204]
Bonjour, 

Je viens vers vous pour vous signaler une erreur lié au champ editor. 
Je pense que TinyMCE on changer leur manière d'utiliser leur bloc de création de contenu HTML car maintenant il réclame une clé API avez-vous des suggestions à faire pour régler ce problème. 
Tout les sites ou nous avons utiliser editor maintenant ils sont en readonly et donc inutilisable ou inchangeable.

Merci d'avance.

**Comment by PrestaSafe** [comment]
Bonjour, 
le soucis est réglé dans la dernière release, voici le détail ici: https://github.com/PrestaSafe/prettyblocks/wiki/Probl%C3%A8me-de-cl%C3%A9-API-du-TinyMCE-(FR) 
Cordialement
