### ISSUE TITLE
TINY MCE key invalid

### ISSUE THREAD

**Issue by bc-devle** [PrestaSafe/prettyblocks#205]
Hello,

Since some days we get the error when editing block with wysiwyg :  
A valid API key is required to continue using TinyMce.
Please alert the admin to check the current API key.
Tried to update module with no success.

What can we do ?
![image (5)](https://github.com/PrestaSafe/prettyblocks/assets/101404772/49720061-e0a1-4c94-bfa2-8c0c06cce456)

**Comment by PrestaSafe** [comment]
Hi. 
This issue is already fixes in the  latest release. 

If you can't update you can fix this by using this issue 

https://github.com/PrestaSafe/prettyblocks/issues/202

You can find the solution is our wiki page

https://github.com/PrestaSafe/prettyblocks/wiki

Thanks

**Comment by bc-devle** [comment]
Hi,
I can't update because it's break a lot of things, I will open another issue for this.
I fixed it applying directly api key in JS assets file.
Thanks
