### ISSUE TITLE
Update problems v2.1.1->v3.0.x

### ISSUE THREAD

**Issue by bc-devle** [PrestaSafe/prettyblocks#206]
Hi,

I can't update because I get many errors : 
- Logo and style changed : OK with reapply
- Blocks positions changed : OK using SQL update to reassign the olds positions with instance_id as key
- 90% of contents from 'config' are not displayed anymore : I can't figure out what happened, I just remarked that content is still in the sql config column. Contents in 'repeaters' are displayed fine.

Tried to update with release and also manually in CLI, no changes.
I use PS1.7.8.11 with cartzilla.

If someone got similar problems or get hints, I take it, thanks

**Comment by PrestaSafe** [comment]
I, thanks for your return, we will make some tests

**Comment by PrestaSafe** [comment]
Hi, we changed the upgrade process, it will be fixed in 3.1. This version coming soon. Thanks
