### ISSUE TITLE
TinyMCE API Key

### ISSUE THREAD

**Issue by Balthorg** [PrestaSafe/prettyblocks#209]
Bonjour,

Il semblerait qu'il y ai un soucis avec la clé API de TinyMCE car les champs "editor" ne sont pas éditable.

Pourtant dans le changelog de la dernière version 3.0.7 il semblerait que ce soit corrigé ?

Merci !

**Comment by PrestaSafe** [comment]
Bonjour voici la solution: 
https://github.com/PrestaSafe/prettyblocks/wiki/Probl%C3%A8me-de-cl%C3%A9-API-du-TinyMCE-(FR)
