### ISSUE TITLE
Debug mode erreur

### ISSUE THREAD

**Issue by fossadierDorian** [PrestaSafe/prettyblocks#216]
Bonjour, 

J'ai cloner et modifier le module classic blocks pour créer mes propre blocks et ça marche bien.

Cependant, quand je me met le mode debug mon backend est en erreur avec ce message include(../composer/InstalledVersions.php): Failed to open stream: No such file or directory.

J'ai bien require_once __DIR__ . '/vendor/autoload.php'; dans mon block. 
J'ai fais composer dump-autoload dans mon block mais toujours l'erreur.

Auriez vous une idée d'où cela pourrais venir.

Cordialement,
Dorian

**Comment by PrestaSafe** [comment]
Bonjour, les classics blocks vous être abandonnés dans peu de temps :) 

rendez vous dans le dossier des classicblocks puis faites un `composer install` 

si cela ne change rien, merci de faire une issue sur le repo en question svp. 

Cordialement
