### ISSUE TITLE
fileupload can't handle non image file

### ISSUE THREAD

**Issue by PubliAlex** [PrestaSafe/prettyblocks#220]
Hello,

It seems that the fileupload field type can just handle images. It is possible to manage other file type with it (eg : pdf) ?

Thank you

**Comment by PrestaSafe** [comment]
it's already done.

**Comment by PubliAlex** [comment]
Hmm, is there a specific field for that ? When I use fileupload field type and upload my PDF, save, but the file array is empty

![image](https://github.com/PrestaSafe/prettyblocks/assets/55833027/8b87e0f2-87e4-4eee-8b41-40c6346f17a1)
