### ISSUE TITLE
Loader still loading on Safari

### ISSUE THREAD

**Issue by CharlesS** [PrestaSafe/prettyblocks#221]
Hi,

I've installed Prettyblocks v3.0.7 on fresh install of Prestashop. Plugin loads well on Chrome and Firefox but not on Safari.

I can navigate website through the iframe, but ZoneArea selector on the top left corner is empty and the button "Chargement en cours" is always visible.

Have you ever faced this issue on Safari ?

Thanks

**Comment by vmulot** [comment]
same here, but not all the times, and on Chrome/Firefox (mac os) latest versions.

**Comment by PrestaSafe** [comment]
Hi, it's maybe a CORS issue. 

is your SSL enable and your certificate well generated ?

**Comment by vmulot** [comment]
i'm in a docker env, with traefik.
website is in https.
it's weird, sometimes it stays at "chargement"  but on clicking on menu item, it works. it seems to be as if  it was random ...

**Comment by PrestaSafe** [comment]
Ok, can try to put header in here ? https://github.com/PrestaSafe/prettyblocks/blob/d6fda1c73ac2129971ca286a656ffd2bbf631323/controllers/front/ajax.php#L69 

Can you try to put `Access-Control-Allow-Origin: null` ? 
Thanks

**Comment by CharlesS** [comment]
Hello, thanks for your reply.
Error still the same after modifying header.

On Chrome or Firefox, when Prettyblocks is launched on homepage, I got 3 XHR requests : 
- /modules/prettyblocks/get_theme_settings/?_token=xxx&ajax=true&ctx_id_lang=0&ctx_id_shop=0
- /modules/prettyblocks/get_theme_settings/?_token=xxx&ajax=true&ctx_id_lang=1&ctx_id_shop=1
- /ajax?ajax=true&action=GetStates&zone=displayHome&ctx_id_lang=1&ctx_id_shop=1&ajax_token=XXXX

But on Safari, I got only the first one : 
- /modules/prettyblocks/get_theme_settings/?_token=xxx&ajax=true&ctx_id_lang=0&ctx_id_shop=0

Thanks

**Comment by CharlesS** [comment]
If you mean JS error throwing by browser, answer is no. 
No error, no warning as well on the server.

**Comment by PrestaSafe** [comment]
Ok thanks, i'll try to make some test on docker. I have not this issus on my local env.

**Comment by CharlesS** [comment]
Thanks a lot :-)

**Comment by vmulot** [comment]
Hello, any news on this issue ? it works with Arc browser, but not in chrome/ff/safari.
No error in console, just some messages :
`Third-party cookie will be blocked. Learn more in the Issues tab.`

**Comment by PrestaSafe** [comment]
hi, not for now, prettyblocks is an open source projet. I'm working on it during my free time for a free software. Thanks.

**Comment by vmulot** [comment]
Ok, i know it's open source and it's a nice idea and tool for Prestashop. i'll try to check by my side if i can find something. i'll let you know.

**Comment by PrestaSafe** [comment]
It's maybe and CORE issue, the wishlist module can make son issue BTW, in the futur version (you can check the `develop` branch) we implement the .dev and you can add more headers to the ajax request and, sometimes, you have to put `null` to the custom headers:

you can try it with this entry in the .env (you need to use the develop version)
`PRETTYBLOCKS_CUSTOM_HEADERS=null,*,'null'`

**Comment by jeremydobber** [comment]
Hello everybody ! 

After facing the same issue with version 3.0.7, I installed a previous release (2.2.0) and it works in the same environment.
Not sure if that information can help...

**Comment by Nossibe63** [comment]
Have you selected a store in the field: “Store being modified” at the top left? If no store is selected, the loader remains displayed...

**Comment by jeremydobber** [comment]
Yes, I have. Unfortunately it does not change anything. I can click, but the loader remains.

**Comment by PrestaSafe** [comment]
Hi, can you try with the `develop` branch ?

**Comment by jeremydobber** [comment]
Hi again! 

I tried again and it happened to work on a local install with v3.0.7 and a dockerized Prestashop 8.1. It does not work on my server however even though the environment is quite similar (docker). The only major difference might be the reverse proxy. Anyway. I'll try to figure it out since this might be an issue specific to my instance.

Thanks!

**Comment by Nimarell** [comment]
Hi,

I did have the issue on Chrome.
It was actually one of my Chrome plugin. Maybe try to disable your plugins and see if it happens again.

**Comment by PubliAlex** [comment]
> Hi,
> 
> I did have the issue on Chrome. It was actually one of my Chrome plugin. Maybe try to disable your plugins and see if it happens again.

Personnaly I tried in incognito mode (so with no plugins) and the problem is still here...

**Comment by PrestaSafe** [comment]
Hi, we changes some params for the iframe. 
It's not fixed :)
