### ISSUE TITLE
Update modules soucis

### ISSUE THREAD

**Issue by Drenore** [PrestaSafe/prettyblocks#224]
Bonjour, 

Désolé encore moi mais je rencontre une autre erreur.
Le soucis ne venant plus du php mais qui a l'air de venir du build, ou du serveur ( que je ne maitrise pas cette fois-çi ). 

Premièrement : 
- Le JS n'arrive plus à retrouver le contexte de la boutique et donc retourne un 0, 0 pour l'id_shop, et l'id_lang.
- Le context de la méthode : 

    updateFilteredURL(url) {
        let hashIndex = url.indexOf('#');
        if (hashIndex !== -1) {
            url = url.substring(0, hashIndex) + '?prettyblocks=1' + url.substring(hashIndex);
        } else if (!url.includes('?')) {
            url += '?prettyblocks=1';
        } else if (!url.includes('prettyblocks')) {
            url += '&prettyblocks=1';
        }
        return url;
    }

return en mettant des valeurs fixes pour le shop et la lang et j'ai eu l'erreur : 

User
 updateFilteredURL(url) {
        console.log(url);
        let hashIndex = url.indexOf('#');
        if (hashIndex !== -1) {
            url = url.substring(0, hashIndex) + '?prettyblocks=1' + url.substring(hashIndex);
        } else if (!url.includes('?')) {
            url += '?prettyblocks=1';
        } else if (!url.includes('prettyblocks')) {
            url += '&prettyblocks=1';
        }
        return url;
    }

TypeError: Cannot read properties of null (reading 'indexOf')
    at g8.updateFilteredURL (index.a5d07f1e.js:48:33172)
    at index.a5d07f1e.js:48:36689
    at kn (index.a5d07f1e.js:16:2020)
    at fn (index.a5d07f1e.js:16:2091)
    at M (index.a5d07f1e.js:16:13265)
    at kn (index.a5d07f1e.js:16:2028)
    at ju (index.a5d07f1e.js:16:3751)
    
    Je sais pas d'où vient le soucis

**Comment by Drenore** [comment]
Une erreur plus lisible ici : 
![image](https://github.com/PrestaSafe/prettyblocks/assets/84106267/bcc05500-9d7a-4fd9-acfb-17b2ee79062d)

**Comment by PrestaSafe** [comment]
Il faut compiler vue et voir l'url en question qui est en défaut. 

https://prettyblocks.io/docs/3/contribute/intro

Cordialement

**Comment by Drenore** [comment]
J'ai fait le test, et j'avais l'url a null

**Comment by Drenore** [comment]
On va monter le site sur un serveur à nous, voir si le soucis vient de leur proxy

**Comment by PrestaSafe** [comment]
Version 3.0.7 ?

**Comment by Drenore** [comment]
Oui c'est bien ça

**Comment by Drenore** [comment]
je fais le test demain et je vous fait un retour directement. 

Bonne soirée, 

Cordialement
