### ISSUE TITLE
problème de langue front/profil back

### ISSUE THREAD

**Issue by vmulot** [PrestaSafe/prettyblocks#227]
Bonjour,
J'ai 2 langues dans mon presta (1: fr, 2: en), la 2 est la langue par défaut en front. mais celle de mon profil est FR.
Quand j'ajoute un block dans un catégorie (j'ai ajouté une zone avec l'id etc), il sauve le block avec la langue du profil à priori et pas la langue par défaut de la boutique.
du coup mes blocs sont save avec id_lang 1 et ne s'affichent pas car en front j'ai id_lang = 2

Prestashop 8.1 et Dernière version de Pretty blocks (v3)

**Comment by PrestaSafe** [comment]
Fixed in 3.1.X :)
