### ISSUE TITLE
Fileupload doesn't work with PDF file (probably all other non image files)

### ISSUE THREAD

**Issue by PubliAlex** [PrestaSafe/prettyblocks#228]
I reopen issue related to this one cause it has probably been closed too fast #220 

I want to precise that I have several pretty blocks setup, lot of them with image upload, and it works well.

But I have a block where I need to upload a PDF, but when the uploaded file is not image one, I get an error (see the loom link below to see the problem).

https://www.loom.com/share/72b7ce07bb4547ca874bbf8bcbdfda18

I'm on 3.7

**Comment by PrestaSafe** [comment]
can you please tell me the details of the error on the javascript console please ? 
The upload folder exists ?

**Comment by PubliAlex** [comment]
The upload folder didn't exists, that was the reason of the error.

In a perfect world, the module should create the folder if doesn't exist, but it's not a critical issue, can be closed
