### ISSUE TITLE
Soucis URL prettyblocks 

### ISSUE THREAD

**Issue by Drenore** [PrestaSafe/prettyblocks#229]
Bonjour, 

Sur un site j'avais des soucis d'upload d'image ( ça a changé récemment ).

Le soucis et maintenant il fait des appelles sur une url erronée. 

Par exemple : 
https://www.futureland.frhttps//www.futureland.fr/accesBO/index.php/modules/prettyblocks/get_theme_settings/?ajax=true&ctx_id_lang=1&ctx_id_shop=1

**Comment by PrestaSafe** [comment]
Bonjour, 
quelle version de prettyblocks avez vous ? 
Pour des raisons de sécurité, je vous invite à masquer les elements sur votre photo ainsi que votre url (surtout du backoffice) je vous conseille vivement de la modifier désormais. 

Nous allons regarder.
