### ISSUE TITLE
Graphic interface display problem when too many block in one zone 

### ISSUE THREAD

**Issue by bc-devle** [PrestaSafe/prettyblocks#23]
There is no max-height and overflow : scroll on blocks menu list items. So when too many items : overflows

See attachments
![bugprettyblock](https://user-images.githubusercontent.com/101404772/222901068-85b3dafb-be54-4297-a998-552070030f62.jpg)

**Comment by PrestaSafe** [comment]
Ho thanks for your issue. We will fix it to the next release.

**Comment by micka-fdz** [comment]
@PrestaSafe I'll make a PR soon to improve global layout (and also fix this issue).
