### ISSUE TITLE
Retrieve block states value for select, multiselect and radio_group fields

### ISSUE THREAD

**Issue by ukoo-jordan** [PrestaSafe/prettyblocks#239]
Pretty Blocks version: **v3.0.7**
Similar closed enhancement: #161

**Issue:** When we try to retrieve the value of the choice from select, multiselect and radio_group fields, we can't do it when we are in the repeater. The issue #161 is exactly the same enhancement but for block settings.

Ex: front type entry dump "Catégorie" which is the translation
![Capture d’écran 2024-08-08 à 11 47 57](https://github.com/user-attachments/assets/f559b0f4-f1e7-40b7-afc4-1746921d0503) 

instead of "category" in PHP:
<img width="300" alt="Capture d’écran 2024-08-08 à 11 49 50" src="https://github.com/user-attachments/assets/727f5c28-b4cb-4d5f-aee3-fb9eb3909d6a">

**Expected result:** having a $block.states_formatted variable, or an array containing value and labels in the existing variable $block.states

**Comment by PrestaSafe** [comment]
Hi, thanks for this issue, indead, we need to implement that soon.

**Comment by PrestaSafe** [comment]
You actually have a `states_json` entry, the value is well display in `value` key :) 
![Capture d’écran 2024-08-15 à 10 04 15](https://github.com/user-attachments/assets/aa220b2f-cbd8-4b93-a484-a74f293dbea2)
