### ISSUE TITLE
Add fields sections

### ISSUE THREAD

**Issue by ukoo-jordan** [PrestaSafe/prettyblocks#242]
**Idea for improvement:** Add the possibility to group fields into differents sections with description which would allow us to give a more presentable display to the final customer. Depending on the blocks created, there may be quite a few fields to create and the configuration panel gradually becomes unreadable. The differents sections would have a visual distinction like larger margins, top and bottom borders, larger size for the section title

**Ex:**
```
Group 1 : Image
Description : This section allow you to configure the image and all attributes related.

Field 1 : Image 
Field 2 : Legend
Field 3 : Loading
Field 4 : Size

Group 2 : Link
Description : This section allow you to configure the link below the image.

Field 1 : Link name
Field 2 : Link 
Field 3 : Target
Field 4 : Color
Field 5 : Size

etc.
```

**Comment by PrestaSafe** [comment]
Hi, we will do that for the V 4
