### ISSUE TITLE
Impossible to deactivate PrettyBlocks default blocks

### ISSUE THREAD

**Issue by ukoo-jordan** [PrestaSafe/prettyblocks#252]
Hi,

**Prettyblock version**: 3.1.0

This new release let us the possibility to remove Prettyblocks default blocks. Unfortunately, when we check the checkbox in Prettyblocks settings, the blocks don't disappear. I uninstalled the module and try again, but result is the same.

Did I do anything wrong?
Thank you! 

NB : Good job for the release!

**Comment by PrestaSafe** [comment]
Hi, thanks to you, i'll fixed it in #251 
you can test it and tell me if it's ok for you ?

**Comment by PrestaSafe** [comment]
Nice !

**Comment by PrestaSafe** [comment]
Thanks you !
