### ISSUE TITLE
Problème multilangue (description produit, catégorie...)

### ISSUE THREAD

**Issue by nmarolleau53** [PrestaSafe/prettyblocks#256]
Bonjour,

Sur mon site multilangue le description produit ou catégorie en anglais ne s'affichent pas.
C'est lié à la fonction _addDynamicZones dans prettyblocks.php en la désactivant cela fonctionne. 
J'étais en 3.1.0 je suis passé en 3.1.1 cela n'a rien changé.

Merci

Prestashop 8.1 et Dernière version de Pretty blocks (v3.1.1)

**Comment by PrestaSafe** [comment]
Bonjour, 

Je n'ai pas ce problème de mon côté. 
![Capture d’écran 2024-09-16 à 09 51 41](https://github.com/user-attachments/assets/37031e8c-b1e3-43c7-82ac-d42551ce9b84)
![Capture d’écran 2024-09-16 à 09 51 23](https://github.com/user-attachments/assets/cb56e595-e36d-4bd3-aa0f-a0593e682014)

Vos descriptions sont bien remplis ? 

Avez vous désactivé l'autofeed ? https://prettyblocks.io/fr/docs/3/dotenv/toolbar#autofeed-zones 

Cordialement
