### ISSUE TITLE
Remove default block option, remove main.css file too

### ISSUE THREAD

**Issue by ukoo-jordan** [PrestaSafe/prettyblocks#260]
If you check the option "Remove default blocks", it doesn't load the main.css anymore.
The problem is, default settings as: "Etirer à 100%" and "Marges internes" or "Marges externes" rely on this file.

**Comment by PrestaSafe** [comment]
Yes, this is normal, we leave the choice to agencies/developers to integrate their own content, blocks and CSS as needed without loading our styles.
We will rework on the translations, or maybe add an other choices for the styles and for the blocks. 

Thanks.
