### ISSUE TITLE
Erreur 500 dès l'install

### ISSUE THREAD

**Issue by herewecom** [PrestaSafe/prettyblocks#266]
Bonjour,

J'ai installé le module v3.1.1 sur un prestashop version 8.0.0 et impossible de le faire tourner.
En mode debug j'ai un "chargement" qui tourne à l'infini et sans debug j'ai une erreur 500 sur /?prettyblocks=1.
Une idée du pourquoi ?

Merci d'avance,
Marie.

**Comment by PrestaSafe** [comment]
Bonjour, 
que vous dit l'erreur 500 svp ? 

Avez vous mis prestashop en debug ? 

Cordialement

**Comment by herewecom** [comment]
Bonjour, 

Alors **sans debug** j'ai :
<img width="1433" alt="Capture d’écran 2024-10-10 à 13 39 11" src="https://github.com/user-attachments/assets/33bc860f-dd42-4a0f-b1ec-fdae21411f1a">
<img width="458" alt="Capture d’écran 2024-10-10 à 13 39 21" src="https://github.com/user-attachments/assets/f946a71f-4c70-4230-ac45-c4c23754ba92">
Et **avec le mode debug**, aucune erreur en console, juste cet appel qui rate et du coup un "chargement" dès que je selectionne la boutique qui tourne dans le vide :
<img width="1438" alt="Capture d’écran 2024-10-10 à 13 42 57" src="https://github.com/user-attachments/assets/da3f8e9a-534c-4db1-be7d-e6f109b3cb4d">

**Comment by PrestaSafe** [comment]
Pouvez vous voir le détail de l'erreur 500 dans la console au au niveau de la requete svp ? 
Dans l'onglet réseau. 

Cordialement

**Comment by herewecom** [comment]
Si c'est plus simple pour vous à regarder je peux vous envoyer des accès par mail. C'est une preprod, ça ne me pose pas de problème.

**Comment by PrestaSafe** [comment]
Bonjour, oui envoyez moi ça par mail svp. Cordialement
