### ISSUE TITLE
Fileupload default value is mandatory and forced by prettyblocks but we don't necessarily need it

### ISSUE THREAD

**Issue by ukoo-jordan** [PrestaSafe/prettyblocks#274]
Hi,

I noticed that the default value for the fileupload field is kind of mandatory, but we don't necessarily need it.
When I remove the default value, It seems that prettyblocks inject this url: https://via.placeholder.com/480x453px

Thank you!

**Comment by PrestaSafe** [comment]
Hi, it's because you have an `insert_default_value` to `true` on your block. This is happen for secure your front end by not blocking the `$block.settings.myfileupload.url`

Thanks.

**Comment by PrestaSafe** [comment]
Your problem is fixed with this pr ?
