### ISSUE TITLE
Incomplete "product" data returned by _getCollection in FieldCore.php

### ISSUE THREAD

**Issue by sarahted** [PrestaSafe/prettyblocks#281]
I’ve encountered an issue with the data returned by the _getCollection method in modules/prettyblocks/classes/prettyblocks/core/FieldCore.php. When attempting to retrieve "product" data, the returned data is incomplete. This seems to occur because the method does not use the appropriate product presenter. As a result, several expected fields are missing from the product data.

Anyway to help with that ? 

Thank you

**Comment by PrestaSafe** [comment]
Hi, can you show me the code of your selector field please ? 
This field return a PrestaShopCollection. 

Thanks.

**Comment by PrestaSafe** [comment]
Hi, thanks for you issue, i'll make some tests this week.
Thanks

**Comment by sarahted** [comment]
Hello, 
I found a way to fix my issue. I use the raw product fetched by pretty blocks & I give a new method I created in Product.php (override) where I use assembler & presenter to enrich my product object & display it correctly.
