### ISSUE TITLE
Use images to illustrate block

### ISSUE THREAD

**Issue by micka-fdz** [PrestaSafe/prettyblocks#71]
We need to add possibility to use images to illustrate a block (not just icon library).
An icon library is not sufficient to illustrate different types of blocks.
I think we should offer the possibility to upload an image (preferably SVG) to use as an illustration.

**Comment by PubliAlex** [comment]
+1 here, I have different kind of text block, choosing 5 differents icons to illustrate them is nonsense whereas a simple screenshot would be easier to understand

**Comment by PrestaSafe** [comment]
Woops, i forgot to close this Issue. It's actually possible by using the `icon_path` option in your block:
 `'icon_path' => 'https://yoursite.com/img/icon.png', // custom icon`
