### ISSUE TITLE
500 error when using PrettyBlocks

### ISSUE THREAD

**Issue by shirleyseywert** [PrestaSafe/prettyblocks#85]
The original theme of Prestashop is working but when using PresstyBlocks, the hopmage only doesn't work. There is a blank page with an error 500

**Comment by PrestaSafe** [comment]
Hi thanks for the feedback. 
Can you tell me the details of this error please ? Prestashop is in debug mode ? Thanks

**Comment by shirleyseywert** [comment]
Fatal error: Uncaught Error: Cannot use object of type Category as array in /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Link.php:443 Stack trace: #0 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Link.php(1500): LinkCore->getCategoryLink(Object(Category), NULL, 2, NULL, NULL, true) #1 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Smarty/SmartyLazyRegister.php(81): LinkCore::getUrlSmarty(Array, Object(SmartyDevTemplate)) #2 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/var/cache/dev/smarty/compile/77/1e/c7/771ec76841bd6b0e403ba93fcd1c1e0eed0dfac6_2.file.product.tpl.php(67): SmartyLazyRegister->__call('getUrlSmarty', Array) #3 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_11435348926480328366b7a1_19123160->callBlock(Object(SmartyDevTemplate)) #4 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_11435348926480328366b7a1_19123160), Object(SmartyDevTemplate)) #5 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process(Object(SmartyDevTemplate), Object(Block_11435348926480328366b7a1_19123160)) #6 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/var/cache/dev/smarty/compile/77/1e/c7/771ec76841bd6b0e403ba93fcd1c1e0eed0dfac6_2.file.product.tpl.php(27): Smarty_Internal_Runtime_Inheritance->instanceBlock(Object(SmartyDevTemplate), 'Block_114353489...', 'product_miniatu...') #7 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6480328367f0c4_85016160(Object(SmartyDevTemplate)) #8 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #9 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #10 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #11 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/var/cache/dev/smarty/compile/db/98/9b/db989bc2092d1e01ce4dfabc6d81b4fda4b6ac9d_2.file.products-list.tpl.php(82): Smarty_Internal_Template->_subTemplateRender('file:catalog/_p...', NULL, NULL, 0, 3600, Array, 0, true) #12 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64803283664f83_70076757(Object(SmartyDevTemplate)) #13 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #14 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #15 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #16 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/var/cache/dev/smarty/compile/14/06/4a/14064a6b847b93777f7c4ec7d24b91d83428a930_2.module.cartzillablocksviewstemplatesblocksproductstrending.tpl.php(43): Smarty_Internal_Template->_subTemplateRender('file:catalog/_p...', NULL, NULL, 0, 3600, Array, 0, false) #17 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6480328364f269_69500690(Object(SmartyDevTemplate)) #18 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #19 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #20 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #21 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/var/cache/dev/smarty/compile/e9/a2/6c/e9a26c0a7fee9c65e27e384c03466e957261e0e0_2.module.prettyblocksviewstemplatesfrontmagic_zone.tpl.php(47): Smarty_Internal_Template->_subTemplateRender('module:cartzill...', NULL, NULL, 0, 3600, Array, 0, true) #22 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_648032836393f3_27749916(Object(SmartyDevTemplate)) #23 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(SmartyDevTemplate)) #24 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(SmartyDevTemplate)) #25 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0) #26 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(SmartyDevTemplate), NULL, NULL, NULL, 0) #27 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Smarty/SmartyDev.php(40): Smarty_Internal_TemplateBase->fetch('module:prettybl...', NULL, NULL, NULL) #28 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/modules/prettyblocks/prettyblocks.php(243): SmartyDev->fetch('module:prettybl...') #29 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/modules/prettyblocks/prettyblocks.php(208): PrettyBlocks::magicZone(Array) #30 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Hook.php(994): PrettyBlocks->renderWidget('displayHome', Array) #31 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Hook.php(938): HookCore::coreRenderWidget(Object(PrettyBlocks), 'displayHome', Array) #32 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/controllers/front/IndexController.php(40): HookCore::exec('displayHome') #33 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/controller/Controller.php(319): IndexControllerCore->initContent() #34 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Dispatcher.php(510): ControllerCore->run() #35 /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/index.php(28): DispatcherCore->dispatch() #36 {main} thrown in /home/clients/750cffd053f851181de79c86d51438f1/sites/grappe.com.dev-djaka.fr/classes/Link.php on line 443

**Comment by PrestaSafe** [comment]
It seems to be a category who doesn't exists anymore, if you bought CartZilla template, please make a ticket on our website we will check this.
