### ISSUE TITLE
Namespace use php keywords

### ISSUE THREAD

**Issue by LaBisquerie** [PrestaSafe/prettyblocks#89]
In the file prettyblocks/classes/HelperBuilder.php l.3, there is this line :
`use PrestaSafe\PrettyBlocks\Core\Interface\BlockInterface;`
Which generates this error when uploading an image, for example :
`Parse error: syntax error, unexpected 'Interface' (T_INTERFACE), expecting identifier (T_STRING) or '{'`
Because `Interface` is a reserved keyword, it cannot be used as a namespace before php 8.

**Comment by PrestaSafe** [comment]
Hi, Thanks for your feed back, we have reproduce the bug, we will fix it. 
It because there is the `Interface` in the namespace and php do not like that... 

Thanks !

**Comment by PrestaSafe** [comment]
fix in #96
