### ISSUE TITLE
Editor field doesn't save style

### ISSUE THREAD

**Issue by mbhwc** [PrestaSafe/prettyblocks#9]
Hey,

Already, thank you for all the work that has been done on this module. I started my tests and it's great.
On the other hand, I have a problem saving HTML tags in the editor field. They don't save to database.
Do you have this problem too?

Thx,
Marie

**Comment by PrestaSafe** [comment]
Hello thanks to you for your feedback . 
Can you give me an exemple please ? 

is it the TinyMCE Component that your talking about ?

**Comment by mbhwc** [comment]
Yes, it's the TinyMCE.
I add a text with a style like strong with the TinyMCE, the modification is ok in the preview. But when I save I keep my text but without the bold style.
I have the impression that on saving all the HTML elements are deleted/cleaned. In database no HTML elements too.

Thx.
Marie.

**Comment by PrestaSafe** [comment]
OK i'll make some test next week :)
